models:
  - type: main
    engine: groq
    model: openai/gpt-oss-120b

rails:
  input:
    flows:
      - check jailbreak
      - mask sensitive data on input
      - check off topic
      - check sensitive topics
      - check secrets input
      - check urgency
  output:
    flows:
      - self check output

  config:
    sensitive_data_detection:
      input:
        entities:
          - PERSON
          - EMAIL_ADDRESS
          - PHONE_NUMBER
          - CREDIT_CARD
